akiba/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from akiba import settings
from akiba import views


urlpatterns = [
    # system URLs
    url(r'^admin/', include(admin.site.urls)),

    # static templates
    url(r'^recent$', views.HomeView.as_view(), name="recent"),
    url(r'^newregister$', views.NewRegisterView.as_view(), name="new_register"),
    url(r'^newlogin$', views.NewLoginView.as_view(), name="new_login"),
    url(r'^thankyou$', views.ThankyouView.as_view(), name="thankyou"),
    url(r'^question$', views.QuestionView.as_view(), name="question"),
    url(r'^comment$', views.CommentView.as_view(), name="comment"),

    # content pages
    url(r'^$', views.HomeView.as_view(), name="index"),
    url(r'^profile/(?P<pk>\d+)$', views.ProfileView.as_view(), name="profile"),
    url(r'^thread/(?P<pk>\d+)$', views.ThreadView.as_view(), name="thread"),
    url(r'^tag/(?P<slug>[-\w]+)$', views.TagView.as_view(), name="tag"),

    url(r'^accounts/register/$', views.AkibaRegistrationView.as_view()),
    url(r'^accounts/', include('registration.backends.hmac.urls')),

    # authenticated users
    url(r'^profile/edit$', views.ProfileEditView.as_view(), name="profile_edit"),
    url(r'^submit$', views.NewThreadView.as_view(), name="new_thread"),
    url(r'^thread/(?P<pk>\d+)/edit$', views.EditThreadView.as_view(), name="edit_thread"),
    url(r'^thread/(?P<thread_id>\d+)/reply$', views.ReplyThreadView.as_view(), name="reply_thread"),
    url(r'^comment/(?P<post_id>\d+)/reply$', views.ReplyCommentView.as_view(), name="reply_comment"),
    url(r'^comment/(?P<post_id>\d+)/delete$', views.DeleteCommentView.as_view(), name="delete_comment"),

    url(r'^thread/(?P<thread_id>\d+)/vote/(?P<verb>up|down)$', views.ThreadLikeView.as_view(), name="thread_like"),
    url(r'^post/(?P<post_id>\d+)/vote/(?P<verb>up|down)$', views.PostLikeView.as_view(), name="post_like"),

    #temporaty pages
    url(r'^profiledisplay$', views.ProfileDisplayView.as_view(), name="profile_edit"),

]

# in debug mode launch debug_toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page
from django.views.static import serve
from django.conf.urls.static import static
from django.http import HttpResponse

from askapp import settings
from askapp import views, api
from askapp.sitemaps import sitemap_dict
from markdownx.urls import urlpatterns as markdownx_urls
#from registration.backends.default.urls import urlpatterns as reg_urls

urlpatterns = [
    # system URLs
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', (markdownx_urls, 'markdownx', 'markdownx')),
    #url(r'^i18n/', django.conf.urls.i18n),
    url(r'^sitemap\.xml$', cache_page(86400)(sitemaps_views.index), {'sitemaps': sitemap_dict, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$', cache_page(86400)(sitemaps_views.sitemap), {'sitemaps': sitemap_dict}, name='sitemaps'),

    # static templates
    # url(r'^newregister$', views.NewRegisterView.as_view(), name="new_register"),
    # url(r'^newlogin$', views.NewLoginView.as_view(), name="new_login"),
    # url(r'^thankyou$', views.ThankyouView.as_view(), name="thankyou"),
    # url(r'^question$', views.QuestionView.as_view(), name="question"),

    # content pages
    url(r'^$', views.HomeView.as_view(), name="index"),
    url(r'^recent$', views.RecentThreadsView.as_view(), name="recent"),
    url(r'^profile/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$', views.ProfileView.as_view(), name="profile"),
    url(r'^thread/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))?/$', views.ThreadView.as_view(), name="thread"),
    url(r'^tag/(?P<slug>[-\w]+)$', views.TagView.as_view(), name="tag"),
    url(r'^domains$', views.DomainsView.as_view(), name="domains"),
    url(r'^domains/(?P<domain>[-\w\.]+)$', views.DomainThreadsView.as_view(), name="domain_thread"),

    #url(r'^accounts/register/$', views.AskappRegistrationView.as_view(), name='register'),
    #url(r'^accounts/', (reg_urls, 'registration', 'registration')),
    url(r'^accounts/', include('allauth.urls')),

    # API
    url(r'api/v1/article/add$', api.AddArticle.as_view(), name="api_add_article"),

    # authenticated users
    url(r'^profile/edit$', views.ProfileEditView.as_view(), name="profile_edit"),
    url(r'^profile/(?P<pk>\d+)/edit$', views.AdminProfileEditView.as_view(), name="admin_profile_edit"),
    url(r'^submit$', views.NewThreadView.as_view(), name="new_thread"),
    url(r'^favorites$', views.FavoriteThreadsView.as_view(), name="favorites"),
    url(r'^thread/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))/edit$', views.EditThreadView.as_view(), name="edit_thread"),
    url(r'^thread/(?P<pk>\d+)(?:/(?P<slug>[\w\d-]+))/delete$', views.DeleteThreadView.as_view(), name="delete_thread"),
    url(r'^thread/(?P<thread_id>\d+)(?:/(?P<slug>[\w\d-]+))/(?P<action>lock|unlock)', views.LockThreadView.as_view(),
        name="lock_thread"),
    url(r'^thread/(?P<thread_id>\d+)(?:/(?P<slug>[\w\d-]+))/reply$', views.ReplyThreadView.as_view(),
        name="reply_thread"),
    url(r'^comment/(?P<post_id>\d+)$', views.ReplyCommentView.as_view(), name="comment_page"),
    url(r'^comment/(?P<post_id>\d+)/delete$', views.DeleteCommentView.as_view(), name="delete_comment"),
    url(r'^comment/(?P<post_id>\d+)/delete_all$', views.DeleteCommentTreeView.as_view(), name="delete_comment_tree"),

    url(r'^thread/(?P<thread_id>\d+)(?:/(?P<slug>[\w\d-]+))/vote/(?P<verb>up|down)$', views.ThreadLikeView.as_view(),
        name="thread_like"),
    url(r'^post/(?P<post_id>\d+)/vote/(?P<verb>up|down)$', views.PostLikeView.as_view(), name="post_like"),
    url(r'^post/(?P<post_id>\d+)/accept$', views.AcceptAnswerView.as_view(), name="accept_answer"),

    url(r'^ytinfo$', views.YoutubeInfo.as_view(), name="youtube_info"),
    # robots.txt
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: * \n Allow: / ", content_type="text/plain")),
]

# in debug mode launch debug_toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', debug_toolbar.urls + ('djdt', )),
    ]

askapp/models.py
import os
import sys
import logging

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django_countries.fields import CountryField
from django.core.files.storage import FileSystemStorage
from io import BytesIO
from django.core.files.uploadedfile import SimpleUploadedFile, InMemoryUploadedFile
from django.db.models.fields.files import ImageFieldFile
from PIL import Image, ImageOps
from mptt.models import MPTTModel, TreeForeignKey
from django.template.defaultfilters import slugify
from urllib.parse import urlparse
from datetime import datetime
import re
import requests

from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError
from django.forms import model_to_dict
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property
import rules_light
from markdownx.models import MarkdownxField
from askapp import settings


class OverwriteStorage(FileSystemStorage):
    """
    When saving an image, this storage class deletes existing file, thus implementing the overwriting feature
    """
    def get_available_name(self, name, *args, **kwargs):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name


def avatar_name_path(instance, filename):
    """
    convert arbitrary file name to the string consisting of username and user ID
    """
    extension = filename[filename.rfind('.'):]
    new_path = 'user_profile/%s%s%s' % (instance.user.username, instance.user.pk, extension)
    return new_path


def favorite_threads(user):
    """
    get list of the threads that user has "upvoted"
    """
    favorites = ThreadLike.objects.filter(user=user, points__gt=0).order_by('-created')
    threads = [f.thread for f in favorites]
    return threads


class AskappImageFieldFile(ImageFieldFile):
    """
    Return default avatar if there is no image
    """
    @property
    def url(self):
        try:
            result = super(AskappImageFieldFile, self).url
            if not os.path.isfile(self.path):
                raise ValueError
        except ValueError:
            result = settings.DEFAULT_AVATAR_URL if hasattr(settings, 'DEFAULT_AVATAR_URL') else ''
        return result


class AskappImageField(models.ImageField):
    attr_class = AskappImageFieldFile


class UserLevel(models.Model):
    """
    User "level" object. Shows how many articles a user with this level can upvote/downvote
    """

    name = models.CharField(blank=False, max_length=100)  # level name
    upvotes = models.IntegerField(default=3, verbose_name='Upvotes per day')  # how many articles a user can upvote per day
    downvotes = models.IntegerField(default=0)
    upvote_same = models.IntegerField(default=1, verbose_name='Upvotes of the same article')  # can user upvote the same article multiple times?
    downvote_same = models.IntegerField(default=1, verbose_name='Downvote same article')

    def __str__(self):
        return str(self.name)


class Profile(models.Model):
    """
    Additional user properties. Attached to the Django user object by 1-to-1 relation
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # 1-to-1 relation to the builtin Django User object
    avatar = AskappImageField(storage=OverwriteStorage(), upload_to=avatar_name_path, blank=True)
    country = CountryField(blank=True)  # country of residence. 3rd party component, saved as ISO code, displayed as full name. Input control is a dropdown list, supporting localisation
    city = models.CharField(max_length=50, blank=True)  # city of residence
    about = models.TextField(max_length=500, blank=True)  # "about me", biography text field
    level = models.ForeignKey(UserLevel, on_delete=models.DO_NOTHING, null=True, default=1)  #  user level, kinda "permissions" in the system

    def __init__(self, *args, **kwargs):
        super(Profile, self).__init__(*args, **kwargs)
        # __original_avatar is used to detect avatar change, to run avatar resize procedure only when needed
        self.__original_avatar = self.avatar

    def __unicode__(self):
        return self.user.username

    @cached_property
    def email(self):
        """
        a helper that allows get email even from the Profile object
        """
        return self.user.email

    def resize_avatar(self):
        # code from with some changes : http://www.yilmazhuseyin.com/blog/dev/create-thumbnails-imagefield-django/
        if not self.avatar:
            return

        try:
            AVATAR_SIZE = settings.AVATAR_SIZE
        except:
            AVATAR_SIZE = (200, 200)

        image = Image.open(BytesIO(self.avatar.read()))
        if self.avatar.name.lower().endswith('png'):
            bg = Image.new("RGB", image.size, (255, 255, 255))
            bg.paste(image, image)
        else:
            bg = image
        min_dimension = min(image.size[0], image.size[1])
        image = ImageOps.fit(bg, (min_dimension, min_dimension))
        image = image.resize(AVATAR_SIZE, Image.ANTIALIAS)

        temp_handle = BytesIO()
        image.save(temp_handle, 'jpeg')
        temp_handle.seek(0)

        suf = SimpleUploadedFile(os.path.split(self.avatar.name)[-1], temp_handle.read(), content_type='image/jpeg')
        self.avatar.save('%s.%s' % (os.path.splitext(suf.name)[0], 'jpg'), suf, save=False)

    def save(self, *args, **kwargs):
        if self.avatar != self.__original_avatar:
            self.resize_avatar()
        super(Profile, self).save(*args, **kwargs)

    @cached_property
    def favorite_threads(self):
        return favorite_threads(self.user)


class Token(models.Model):
    """
    An access token that is associated with a user.  This is essentially the same as the token model from Django REST Framework
    """
    key = models.CharField(max_length=40, primary_key=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)

    def generate_key(self):
        import binascii
        return binascii.hexlify(os.urandom(20)).decode()

    def __unicode__(self):
        return self.key


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created or not hasattr(instance, 'profile'):
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


@receiver(post_save, sender=User)
def delete_user_content(sender, instance, created, **kwargs):
    """
     Signal handler running after Django.user object is saved.
     For disabled user it marks as "deleted" all user's threads and posts
    """
    if not instance.is_active:
        if kwargs['update_fields'] and 'is_active' in kwargs['update_fields']:
            # Perform posts/threads deletion only when is_active field was explicitly mentioned for update
            # delete user threads and posts
            Post.objects.filter(user_id=instance.id, deleted=False).update(deleted=True)
            Thread.objects.filter(user_id=instance.id, deleted=False).update(deleted=True)


class Tag(models.Model):
    """
    Thread tags
    """
    name = models.CharField(max_length=60, null=False)  # full tag name
    slug = models.SlugField(max_length=60, null=False)  # slugified tag name to use in URLs

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return "{0}".format(self.name)


class Thread(models.Model):
    """
    Thread is the main content object of the application
    """
    # codes for types of posts
    QUESTION = "QQ"
    DISCUSSION = "DD"
    LINK = "LL"
    YOUTUBE = "YT"
    DUPLICATE = "DU"
    VIDEOSTREAM = "VS"

    # iterable collection for types of posts
    # must consist of iterables of exactly two items
    TYPES_OF_THREAD = (
        #(QUESTION, _('Question')),
        (DISCUSSION, _('Discussion')),
        (LINK, _('Link')),
        (YOUTUBE, _('Youtube video')),
        (DUPLICATE, _('Duplicate thread')),
        (VIDEOSTREAM, _('Video stream')),
    )
    TYPES_WITH_LINK = [LINK, YOUTUBE, DUPLICATE, VIDEOSTREAM]

    #many to many relationship with tags. When a post is created, it needs to be saved and then tags can be added
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=_('tags'))

    # these fields are taken into account only if the post is thread starter
    hidden = models.BooleanField(default=False)  # the thread is visible only to the staff and the author
    closed = models.BooleanField(default=False)  # no one can post comments / answers in this thread
    sticky = models.DateField(null=True, blank=True)  # this thread will be sticky until the given date
    featured = models.BooleanField(default=False)  # hopefully one day there will be sponsored threads...
    deleted = models.BooleanField(default=False)  # the thread is marked as deleted, usually on user blocking

    # reference to the user who created the post
    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE, default=1)

    # atomatically added timestamp field when the record is created
    created = models.DateTimeField(auto_now_add=True)

    # atomatically added timestamp field when the record is modified
    modified = models.DateTimeField(auto_now=True)

    # Thread must have one of the types defined in TYPES_OF_THREAD
    thread_type = models.CharField(
        max_length=2,
        choices=TYPES_OF_THREAD,
        default=LINK,
        null=True
    )

    # thread body with HTML markup

askapp/templates/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static "images/favicon.png" %}">

    {# Load CSS and JavaScript #}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
    {% bootstrap_javascript %}
    {% bootstrap_css %}

    {% block css %}
        <link rel="stylesheet" href="{% static "style.css" %}" />
    {% endblock %}

    <title>
        {% block title %}
            {{ site_name }}
        {% endblock %}
    </title>

    <meta name="description" content="{% block description %}{{ about_text }}{% endblock %}">
    <script>
    {% if google_analytics_id %}
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '{{ google_analytics_id }}', 'auto');
      ga('send', 'pageview');
    {% endif %}

      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!/^(GET|HEAD|OPTIONS|TRACE)$/.test(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
              }
          }
      });
    </script>
</head>

<body>

{#----------------header-------------------------#}
{% block header %}
    {% load askapp_filters %}
    <nav class="navbar navbar-default">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">
                  {% if site_logo %}<img src="{{ get_media_prefix }}{{ site_logo }}"/>{% endif %}
                  {{ site_name }}
                </a>
            </div>


            <div id="navbar" class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li class="{% url_active 'index' %}"><a href="{% url 'index' %}">Top</a></li>
                    <li class="{% url_active 'recent' %}"><a href="{% url 'recent' %}">Recent</a></li>
                    {% if user.is_authenticated %}
                    <li class="{% url_active 'favorites' %}"><a href="{% url 'favorites' %}">Favorite posts</a></li>
                    {% endif %}
                    <li class="{% url_active 'new_thread' %}"><a href="{% url 'new_thread' %}">Submit post</a></li>

                </ul>


                <div class="nav navbar-btn navbar-right">
                    {% if user.is_authenticated %}
                        Logged in: <a href="{% url 'profile_edit' %}">{{ user.username }}</a>
                        (<a href="{% url 'account_logout' %}">Log out</a> )
                    {% else %}
                        <a href="{% url 'account_login' %}" class="btn btn-link">Login</a>
                        <a href="{% url 'account_signup' %}" class="btn btn-primary">Register</a>
                    {% endif %}


                </div>

            </div>
        </div>
    </nav>
{% endblock %}
{# --------------------- end header -------------------------#}


<div class="container">

    <div class="row">

        {#--------------main column ----------------#}
        <div class="col-md-9">
            {% block messages %}{% endblock %}
            {% block content %}
                this is the content block
            {% endblock %}

        </div>
        {#--------------end main column ----------------#}


        {#--------------right column ----------------#}
        <div class="col-md-3 visible-md-block visible-lg">
            {% block rightcolumn %}
            {% endblock %}

        </div>
        {#--------------end right column ----------------#}

    </div>
</div>


<footer class="footer" style="background-color: #adadad">
    <div class="container">

        {% block footer %}

            <div class="navbar-default">
                <div class="col-sm-12 col-lg-3">
                    <span class="navbar-brand"> &copy; {% now "Y" %} <a href="{% url 'index' %}">{{ site_name }}</a></span>
                </div>
                <div class=" col-sm-12 col-lg-5">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'recent' %}">Recent</a></li>
                        <li><a href="{% url 'new_thread' %}">Submit post</a></li>

                    </ul>
                </div>

                <div class="col-sm-12 col-lg-4">
                    <span class="navbar-brand"> Powered by <a href="http://askapp.org">askapp.org</a></span>
                </div>
            </div>

        {% endblock %}
    </div>
</footer>
</body>

</html>

askapp/templates/new_thread.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}Submit new thread{% endblock %}



{% block content %}
    <div class="row col-md-6">
        <form method="post" enctype="multipart/form-data">
	        {% csrf_token %}
            {% if not form.instance.pk %}
            <div class="form-group">
	            <label for="id_thread_type">Type:</label>
	            {{ form.thread_type }}
            </div>
            {% endif %}
            {% if not form.instance.pk or form.instance.thread_type == 'LL' %}
            <div class="form-group" id="url_group">
	            <label for="id_link">URL:</label>
	            {{ form.link }}
	            {{ form.link.errors }}
            </div>
            {% endif %}
            <div class="form-group">
	            <label for="id_title">Title:</label>
	            {{ form.title }}
	            {{ form.title.errors }}
            </div>
            <div class="form-group">
	            <label for="id_text">Summary:</label>
	            {{ form.text }}
	            {{ form.text.errors }}
            </div>
            <div class="form-group">
	            <label for="id_tags">Tags:</label>
	            {{ form.tags }}
	            {{ form.tags.errors }}
            </div>
            <div class="form-group">
	            <label for="id_image">Image:</label>
	            {% if form.image.value %}
		            <img src="{{ MEDIA_URL }}{{ form.image.value }}" />
	            {% endif %}
	            {{ form.image }}
	            {{ form.image.errors }}
            </div>

            <button type="submit" class="btn btn-primary pull-right">Submit</button>
        </form>
    </div>

<script>
$('#id_thread_type').on('change', function() {
	if ($(this).val() == 'LL')
		$('#url_group').show();
	else
		$('#url_group').hide();
});
$('#id_thread_type').triggerHandler('change');
</script>
{% endblock %}


{% block rightcolumn %}
    {#    <user class="is_a"></user>uthenticated %}#}
    {#        <p>You are already logged in.#}
    {#        </p>#}
    {#    {% else %}#}
    {#        <p>You are not logged in?!</p>#}
    {#    {% endif %}#}



{% endblock %}

askapp/templates/thread_edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}{% if not form.instance.pk %}Submit new{% else %}Edit{% endif %} thread{% endblock %}

{% block content %}
    <div class="row col-md-6">
        <form method="post" enctype="multipart/form-data">
	        {% csrf_token %}
            {% if not form.instance.pk or admin_view %}
            <div class="form-group">
	            <label for="id_thread_type">Type:</label>
	            {{ form.thread_type }}
            </div>
            {% endif %}
            {% if not form.instance.pk or admin_view or form.instance.thread_type in 'DU' %}
            <div class="form-group" id="duplicate_group">
	            <label for="id_original">Original thread ID:</label>
	            {{ form.original }}
	            {{ form.original.errors }}
            </div>
            {% endif %}
            {% if not form.instance.pk or admin_view or form.instance.thread_type in 'LL,YT,DU,VS' %}
            <div class="form-group" id="url_group">
	            <label for="id_link" id="id_link_label">URL:</label>
	            {{ form.link }}
              <button id="yt_group" onclick="return preload_youtube()" class="btn btn-info">Preload</button>
	            {{ form.link.errors }}
            </div>
            {% endif %}
            <div class="form-group">
	            <label for="id_title">Title:</label>
	            {{ form.title }}
	            {{ form.title.errors }}
            </div>
            <div class="form-group">
	            <label for="id_text">Summary:</label>
	            {{ form.text }}
	            {{ form.text.errors }}
            </div>
            <div class="form-group">
	            <label for="id_tags">Categories:</label>
	            {{ form.tags }}
	            {{ form.tags.errors }}
            </div>
            <div class="form-group">
	            <label for="id_image">Image:</label>
	            {% if form.image.value %}
		            <img src="{{ MEDIA_URL }}{{ form.image.value }}" />
	            {% endif %}
	            {{ form.image }}
	            {{ form.image.errors }}
            </div>

            <button type="submit" class="btn btn-primary pull-right">Submit</button>
        </form>
    </div>

{{ form.media }}
<script>
{% if admin_view %}
  $('form').on('submit', function(data, q) {
      if ($('#id_thread_type').val() != 'DU')
          $('#id_original').val('')
      return true
  })
{% endif %}

{% if not form.instance.pk or admin_view %}
function preload_youtube() {
  url = $('#id_link').val();
  $.getJSON('{% url 'youtube_info' %}?q='+url, function(data) {
    $('#id_title').val(data.title);
    $('#id_text').val(data.description);
    img = $('.form-group img');
    if (!img.length)
      img = $('#id_image').before('<img src="'+data.image+'" />');
    else
      img.attr('src', data.image);
  }).error(function() {
    alert('This is not a valid YouTube URL');
    $('#id_link').val('').triggerHandler('input');
  });
  return false;
}
$('#id_thread_type').on('change', function() {
	if ($.inArray($(this).val(), ['LL', 'YT', 'DU', 'VS']) >= 0) {
      $('#url_group').show();
      if ($(this).val() == 'VS')
          $('#id_link_label').text('Stream URL:')
      else
          $('#id_link_label').text('URL:')
  } else
		$('#url_group').hide();
  if ($('#id_thread_type').val() == 'YT')
    $('#yt_group').show();
  else
    $('#yt_group').hide();
  if ($('#id_thread_type').val() == 'DU')
      $('#duplicate_group').show();
  else
      $('#duplicate_group').hide();
});
$('#id_link').on('input', function () {
  if (this.value)
    $('#yt_group').removeAttr('disabled');
  else
    $('#yt_group').attr('disabled', 'disabled')
})
$('#id_thread_type').triggerHandler('change');
$('#id_link').triggerHandler('input');
{% endif %}
</script>
{% endblock %}


{% block rightcolumn %}
{% endblock %}